modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/HungryTools/issues"
license="MIT"

[[mods]]
modId="hungrytools"
version="${file.jarVersion}"
displayName="Hungry Tools"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hungry-tools"
authors="Mrbysco"
description='''
Your tools are now hungry! Go and feed them!
'''
[[dependencies.hungrytools]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.hungrytools]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="hungrytools.mixins.json"